### ISSUE TITLE
CellStructure and get_search_spaces files was not found

### ISSUE THREAD

**Issue by zekikus** [automl/DE-NAS#2]
Hi,

I get an error when I try to **run_de_nas201.py** code. I cannot find **CellStructure** and **get_search_spaces** files in AutoDL-Projects repo. I guess these files were removed from the main repo. Can you release models folder and CellStructure, get_search_spaces files, if you have?

![image](https://user-images.githubusercontent.com/7164423/138947354-fa03ecd7-a292-4c33-911d-c6b2d17f5623.png)

Thanks,

**Comment by Neeratyoy** [comment]
Hi,

The `examples` scripts are only supposed to serve as templates. None of the benchmark code is part of this repository. Please follow the [README](https://github.com/automl/DE-NAS/blob/master/denas/examples/README.md) guidelines as they should help provide the dependencies to bypass the error you report.

Additionally, please note, the scripts are not expected to run off-the-shelf and may need minor changes. Since the benchmark codes (such as NAS-201) might have been updated.

Given that this is not an issue with the `DE` code in this repository. I am closing this `issue`. 
Please feel free to discuss further regarding this, or through new issues! :)

**Comment by zekikus** [comment]
Thank you for your help.
